// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Order struct {
	ID         string
	Price      sql.NullString
	Tax        sql.NullString
	FinalPrice sql.NullString
}
